baseurl = "https://www.longbranchchurch.org"
DefaultContentLanguage = "en"
title = "Long Branch Church"
#theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "G-Z265E06J10"

# Required for inlining iframes, divs, and other markup
# in the markdown (i.e. .md) files
[markup.goldmark.renderer]
unsafe = true

[module]
  proxy = "direct"  
  [module.hugoVersion]
    min = "0.104.2"
  [[module.imports]]
    path = "github.com/f3carpex/beautifulhugo"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Believe Belong Become"
  mainSections = ["post","posts"]
  logo = "img/brand/LBCLogo.png" # Expecting square dimensions
  darkLogo = "img/brand/LBCLogo.png"
  favicon = "img/brand/LBCLogo.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "img/LBCFront.jpg"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[taxonomies]
  # keep default taxonomies
  category = 'categories'
  tag = 'tags'
  # new taxonomies for backblasts
  ao = 'AOs'
  pax = 'pax'

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
#   name = "Some Person"
#   website = "yourwebsite.com"
#   email = "youremail@domain.com"
  facebook = "f3caryapex"
#  github = "longbranchpfwbchurch"
#   gitlab = "username"
#   bitbucket = "username"
#  twitter = "username"
#   reddit = "username"
#   linkedin = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#  instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"
#   500px = "username"
#   codepen = "username"
#   mastodon = "url"
#   kaggle = "username"
#   weibo = "username"
#  slack = "username"
#   discord = "invite code (https://discord.gg/XXXXXXX)"
#   strava = "userid"

[[menu.main]]
    identifier = "our church"
    name = "About Us"
    url = "About Us/"
    weight = 1

[[menu.main]]
    parent = "our church"
    name = "Leadership"
    url = "leadership/"
    weight = 2

[[menu.main]]
    parent = "our church"
    name = "About Us"
    url = "About Us/"
    weight = 3

[[menu.main]]
    parent = "our church"
    name = "2nd F (Fellowship)"
    url = "schedule/#2ndf"
    weight = 4

[[menu.main]]
    identifier = "pax"
    name = "PAX"
    weight = 40

[[menu.main]]
    parent = "pax"
    name = "New to F3"
    url = "new-to-f3/"
    weight = 41

[[menu.main]]
    name = "Stay in touch"
    url = "contact/"
    weight = 50
